"""initial_db_struct

Revision ID: 2306039e9901
Revises: f1cd3b5e1dec
Create Date: 2024-11-29 17:30:35.883005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2306039e9901'
down_revision: Union[str, None] = 'f1cd3b5e1dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('profile', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('gender', sa.BOOLEAN(), nullable=True),
    sa.Column('birthday', mysql.DATETIME(), nullable=True),
    sa.Column('introduction', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('follower_num', mysql.INTEGER(), server_default='0', nullable=False),
    sa.Column('following_num', mysql.INTEGER(), server_default='0', nullable=False),
    sa.Column('role', mysql.ENUM('ADMIN', 'USER'), server_default='USER', nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('agreement',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('term', mysql.BIT(length=3), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debate',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('isbn', mysql.VARCHAR(length=13), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('held_at', mysql.DATETIME(), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('image1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('image2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('likes_num', mysql.INTEGER(unsigned=True), server_default='0', nullable=False),
    sa.Column('comments_num', mysql.INTEGER(unsigned=True), server_default='0', nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('my_book',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('isbn', mysql.VARCHAR(length=13), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth',
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('registration', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('image1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('image2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('likes_num', mysql.INTEGER(unsigned=True), server_default='0', nullable=False),
    sa.Column('comments_num', mysql.INTEGER(unsigned=True), server_default='0', nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summary',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('isbn', mysql.VARCHAR(length=13), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('free_content', mysql.JSON(), nullable=True),
    sa.Column('charged_content', mysql.JSON(), nullable=True),
    sa.Column('price', mysql.INTEGER(), server_default='0', nullable=False),
    sa.Column('image1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('image2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('likes_num', mysql.INTEGER(unsigned=True), server_default='0', nullable=False),
    sa.Column('comments_num', mysql.INTEGER(unsigned=True), server_default='0', nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debate_comment',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('debate_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('content', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column('likes_num', mysql.INTEGER(unsigned=True), server_default='0', nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['debate_id'], ['debate.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debate_like',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('debate_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['debate_id'], ['debate.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_comment',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('post_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('content', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column('likes_num', mysql.INTEGER(unsigned=True), server_default='0', nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_like',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('post_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summary_comment',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('summary_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('content', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column('likes_num', mysql.INTEGER(), server_default='0', nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['summary_id'], ['summary.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summary_like',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('summary_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['summary_id'], ['summary.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debate_comment_like',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('debate_comment_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['debate_comment_id'], ['debate_comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_comment_like',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('post_comment_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['post_comment_id'], ['post_comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summary_comment_like',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('summary_comment_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['summary_comment_id'], ['summary_comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('summary_comment_like')
    op.drop_table('post_comment_like')
    op.drop_table('debate_comment_like')
    op.drop_table('summary_like')
    op.drop_table('summary_comment')
    op.drop_table('post_like')
    op.drop_table('post_comment')
    op.drop_table('debate_like')
    op.drop_table('debate_comment')
    op.drop_table('summary')
    op.drop_table('post')
    op.drop_table('oauth')
    op.drop_table('my_book')
    op.drop_table('debate')
    op.drop_table('agreement')
    op.drop_table('user')
    # ### end Alembic commands ###
