"""message

Revision ID: 50414375913e
Revises: e9b45e9d000c
Create Date: 2025-02-19 09:58:27.262255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '50414375913e'
down_revision: Union[str, None] = 'e9b45e9d000c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debate', sa.Column('limit', mysql.INTEGER(unsigned=True), server_default='0', nullable=False))
    op.alter_column('user', 'role',
               existing_type=mysql.ENUM('ADMIN', 'USER'),
               server_default='USER',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=mysql.ENUM('ADMIN', 'USER'),
               server_default=sa.text("'USER'"),
               existing_nullable=False)
    op.drop_column('debate', 'limit')
    # ### end Alembic commands ###
