"""initialize

Revision ID: d0cd9179a860
Revises: 
Create Date: 2025-01-09 14:51:26.265026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd0cd9179a860'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('isbn', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('image', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('author', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('publisher', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('pubdate', sa.DATE(), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('isbn')
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('profile', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('gender', sa.BOOLEAN(), nullable=True),
    sa.Column('birthday', mysql.DATETIME(), nullable=True),
    sa.Column('introduction', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('follower_num', mysql.INTEGER(), server_default='0', nullable=False),
    sa.Column('following_num', mysql.INTEGER(), server_default='0', nullable=False),
    sa.Column('role', mysql.ENUM('ADMIN', 'USER'), server_default='USER', nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default='0', nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('agreement',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('term', mysql.BIT(length=3), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debate',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('isbn', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('link', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('held_at', mysql.DATETIME(), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('comments_num', mysql.INTEGER(unsigned=True), server_default='0', nullable=False),
    sa.Column('likes_num', mysql.INTEGER(unsigned=True), server_default='0', nullable=False),
    sa.Column('files', mysql.JSON(none_as_null=True), nullable=True),
    sa.ForeignKeyConstraint(['isbn'], ['book.isbn'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('following',
    sa.Column('follower_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('following_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'following_id')
    )
    op.create_table('my_book',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('isbn', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['isbn'], ['book.isbn'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth',
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('provider', mysql.ENUM('KAKAO', 'NAVER', 'GOOGLE', 'FACEBOOK'), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('comments_num', mysql.INTEGER(unsigned=True), server_default='0', nullable=False),
    sa.Column('likes_num', mysql.INTEGER(unsigned=True), server_default='0', nullable=False),
    sa.Column('files', mysql.JSON(none_as_null=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('product_type', mysql.ENUM('D', 'S'), nullable=False),
    sa.Column('product_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('content', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('price', mysql.INTEGER(), nullable=False),
    sa.Column('quantity', mysql.INTEGER(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default='0', nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summary',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('isbn', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('free_content', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('charged_content', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('price', mysql.INTEGER(), server_default='0', nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('comments_num', mysql.INTEGER(unsigned=True), server_default='0', nullable=False),
    sa.Column('likes_num', mysql.INTEGER(unsigned=True), server_default='0', nullable=False),
    sa.Column('files', mysql.JSON(none_as_null=True), nullable=True),
    sa.ForeignKeyConstraint(['isbn'], ['book.isbn'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debate_comment',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('debate_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('upper_comment_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('content', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('comments_num', mysql.INTEGER(unsigned=True), server_default='0', nullable=False),
    sa.Column('likes_num', mysql.INTEGER(unsigned=True), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['debate_id'], ['debate.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upper_comment_id'], ['debate_comment.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debate_like',
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('debate_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['debate_id'], ['debate.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'debate_id')
    )
    op.create_table('post_comment',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('post_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('upper_comment_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('content', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('comments_num', mysql.INTEGER(unsigned=True), server_default='0', nullable=False),
    sa.Column('likes_num', mysql.INTEGER(unsigned=True), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upper_comment_id'], ['post_comment.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_like',
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('post_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.create_table('summary_comment',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('summary_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('upper_comment_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('content', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('comments_num', mysql.INTEGER(unsigned=True), server_default='0', nullable=False),
    sa.Column('likes_num', mysql.INTEGER(unsigned=True), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['summary_id'], ['summary.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upper_comment_id'], ['summary_comment.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summary_like',
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('summary_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['summary_id'], ['summary.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'summary_id')
    )
    op.create_table('debate_comment_like',
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('debate_comment_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['debate_comment_id'], ['debate_comment.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'debate_comment_id')
    )
    op.create_table('post_comment_like',
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('post_comment_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['post_comment_id'], ['post_comment.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_comment_id')
    )
    op.create_table('summary_comment_like',
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('summary_comment_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['summary_comment_id'], ['summary_comment.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'summary_comment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('summary_comment_like')
    op.drop_table('post_comment_like')
    op.drop_table('debate_comment_like')
    op.drop_table('summary_like')
    op.drop_table('summary_comment')
    op.drop_table('post_like')
    op.drop_table('post_comment')
    op.drop_table('debate_like')
    op.drop_table('debate_comment')
    op.drop_table('summary')
    op.drop_table('purchase')
    op.drop_table('post')
    op.drop_table('oauth')
    op.drop_table('my_book')
    op.drop_table('following')
    op.drop_table('debate')
    op.drop_table('agreement')
    op.drop_table('user')
    op.drop_table('book')
    # ### end Alembic commands ###
